// Public pull zone URLs. No API key, no storage calls, so this is safe to
// import from a client component — src/lib/bunny.ts is not.

const PULL_ZONE = process.env.NEXT_PUBLIC_BUNNY_PULL_ZONE;

export interface BunnyTransform {
  width?: number;
  height?: number;
  /** 1-100. Bunny defaults to 85. */
  quality?: number;
}

/** Caps the source width so the optimiser never resizes a 39 MB PNG. */
const MAX_SOURCE_WIDTH = 1600;

export function bunnyUrl(path: string, t?: BunnyTransform): string {
  if (!PULL_ZONE) {
    console.warn(
      "NEXT_PUBLIC_BUNNY_PULL_ZONE is not set in your environment — " +
        "returning the path unchanged, which will 404. Check your .env.local.",
    );
    return path;
  }

  const base = PULL_ZONE.replace(/\/$/, "");
  const clean = path.startsWith("/") ? path : `/${path}`;
  const url = `${base}${clean}`;

  // Optimizer parameters. Inert unless the add-on is enabled on the zone, and
  // it is deliberately off — everything is pre-generated by the ladder.
  const q = new URLSearchParams();
  const width = t?.width ?? MAX_SOURCE_WIDTH;
  if (width) q.set("width", String(width));
  if (t?.height) q.set("height", String(t.height));
  if (t?.quality) q.set("quality", String(t.quality));

  const qs = q.toString();
  return qs ? `${url}?${qs}` : url;
}
